### PR TITLE
change from `discordapp.com` to `discord.com`

### PR DESCRIPTION
**Pull request by mischievousdev**

### CODE REVIEW

**Comment by fourjr** [comment]
Hi, thanks for the PR. The tests are still using old endpoint, discordapp.com, thus Travis is failing.

Will merge when this is fixed.

**Comment by mischievousdev** [comment]
Ok

**Comment by mischievousdev** [comment]
I think now travis build won't fail, coz of latest push

**Comment by kyb3r** [comment]
#36 has made this PR obsolete right?

**Pull request closed without merging**
